# Generated by Django 5.0 on 2023-12-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffrole_staffregister_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregister',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
