# Generated by Django 5.0 on 2023-12-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffregister_login_credential_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregister',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffregister',
            name='otp',
            field=models.CharField(blank=True, default='658734', max_length=10),
        ),
    ]
