# Generated by Django 5.0 on 2024-01-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('report_charge', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
