# Generated by Django 5.0 on 2024-01-06 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='piad_payment',
            new_name='paid_payment',
        ),
    ]
