# Generated by Django 5.0 on 2024-01-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_rename_piad_payment_patient_paid_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='paid_payment',
        ),
        migrations.AddField(
            model_name='patient',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='remaining_amount',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='total_amount',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
