# Generated by Django 5.0 on 2024-01-09 08:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_remove_patient_paid_payment_patient_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='paid_installment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('paid_date', models.DateField(default=datetime.date(2024, 1, 9))),
                ('paid_payment', models.FloatField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
