# Generated by Django 5.0 on 2024-01-09 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_paid_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid_installment',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 9, 15, 14, 115055, tzinfo=datetime.timezone.utc)),
        ),
    ]
