# Generated by Django 5.0 on 2024-01-09 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_alter_paid_installment_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid_installment',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 9, 31, 23, 890860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
